### ISSUE TITLE
"Acastus Photon" name translation

### ISSUE THREAD

**Issue by lucamp** [gjedeer/Acastus#12]
Hi,
Photon means an elementary particle and not photo (image) as it has been translated in Italian, Portuguese, Brazilian and Spanish.

Please read:
https://github.com/komoot/photon/issues/456

In Italian it could be translated to "Acastus Fotone", but honestly I do not see a reason why to translate its original name since Photon is a program name, decided by their developers.

Since the name "Acastus Photon" is easy recognizable by any Latin based languages I suggest just to stick to its original German name, which is also the same in English, and not translating to other languages, it will be more consistent.

I already suggested "Acastus Photon" as Italian translation in crowdin, but others are wrong.

Please share your opinion in this issue.

Thanks
Luca

**Comment by gjedeer** [comment]
LOL I had no idea this is happening. It should definitely be named "Photon" as in English, I'd also laugh hard if someone named it "akastus foton" in Polish.

By all means please do change it back to Photon.

**Comment by gjedeer** [comment]
PS, did thay rename Firefox to volpe di fuoco too? (google translate helped me with this one)

**Comment by lucamp** [comment]
> PS, did thay rename Firefox to volpe di fuoco too? (google translate helped me with this one)

Not yet, hope it will never ever be and pretty sure that will not happen since it's a well known "brand".
However other programs are doing that and sometimes it could be reasonable like "File Manager" to " Gestore di File" or "Gallery" to "Galleria" since the name is used to give a meaning of what the app will do.
Hope they not apply these thoughts to Firefox, maybe someone will launch it trying to light a stove O_o

**Comment by Elaborendum** [comment]
I don't know if it's the right place to ask, but I just downloaded the app, and it still has the name translated. Checking the source, it seems like some languages haven't been updated in 2 years?

**Comment by gjedeer** [comment]
There you go:

https://github.com/gjedeer/Acastus/commit/08ebb8351c506527929a9df850498d889a39e76e

PS. It looks like only 53% of strings are translated to Italian - maybe one of the people from this thread would like to translate the rest? https://crowdin.com/project/acastus-photon-adress2geotrans

**Comment by Elaborendum** [comment]
Thanks. Just one more thing, Spanish, French, Portuguese and Swedish still seem to have the name translated.

**Comment by k3b** [comment]
@Elaborendum @gjedeer  I just made app_name="Acastus Photon" non translateable

**Comment by gjedeer** [comment]
@k3b nice!
