### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [gjedeer/Acastus#14]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by gjedeer** [comment]
Hey, no reason to close just because it wasn't done immediately

**Comment by gjedeer** [comment]
PS. your pull request is welcome

**Comment by k3b** [comment]
I have added an image which is also visible on the Startpage
