### ISSUE TITLE
New F-Droid-Release "1.22"

### ISSUE THREAD

**Issue by k3b** [gjedeer/Acastus#15]
I have just initiated a new Release for F-Droid that should be available in a few days

**Comment by gjedeer** [comment]
@k3b I'd like to release 1.23 when someone confirms it works, I've been a bit out of the loop recently. 

These days, is it enough to bump version in app/build.gradle and tag 1.23 in git repo? Or will I need to bump version in fdroiddata repo too?

**Comment by k3b** [comment]
I have done this for version 1.22:

* increment versionCode and versionName in  [app/build.gradle](https://github.com/gjedeer/Acastus/blob/master/app/build.gradle)
  * i.e. versionCode 23
  * i.e. versionName "1.23"
* create or update changelog textfile with {versionCode}.txt and put in what you have changed
  * i.e. your new changes goe here [fastlane/metadata/android/en-US/changelogs/23.txt](https://github.com/gjedeer/Acastus/blob/master/fastlane/metadata/android/en-US/changelogs/23.txt)
  * i.e. my last changes where [fastlane/metadata/android/en-US/changelogs22.txt](https://github.com/gjedeer/Acastus/blob/master/fastlane/metadata/android/en-US/changelogs/22.txt)
* Create a tag in git repository that has the exact  versionName 
  *  i.e. "1.23"

**Comment by gjedeer** [comment]
Thanks a lot!

**Comment by k3b** [comment]
when i create a new release i alwaqys crete the changes file for the next release where i can add what i am currently changing. in your case create an empty 24.txt

**Comment by k3b** [comment]
before releaseing next version let-s see if the screenshot image works as expected. I am not shure if the file format/size is ok

**Comment by gjedeer** [comment]
Makes sense with 24.txt, I've added it.

Screenshot -> OK, will wait. Nice idea with the visual explanation in the screenshot.

**Comment by gjedeer** [comment]
Hmm, I can see 1.22 in F-Droid but the screenshot doesn't seem to be there.

**Comment by gjedeer** [comment]
Looking at the docs and other apps from F-Droid, I think it's because the screenshots need to be sequential numbers (01.png, 02.png, etc). I renamed the file to `01.png`.

You think it's OK to tag 1.23 now?

**Comment by k3b** [comment]
shure

**Comment by k3b** [comment]
@gjedeer the screenshot is now visible in f-droid for version 1.22.

since you renamed the screenshot file to 01.png  i also renamed the image-link in the readme.md so now it is visible again

**Comment by gjedeer** [comment]
@k3b sorry - at the time when I checked, the screenshot wasn't working. Maybe it was my network.

**Comment by k3b** [comment]
close this ticket because screenshot is now visible
