### ISSUE TITLE
Support for geo:0,0?q=[search]

### ISSUE THREAD

**Issue by leso-kn** [gjedeer/Acastus#16]
Many apps use the `q` parameter of the `geo:` uri scheme (e.g. Etar on F-Droid) to pass places to other apps.
Nevertheless not many apps support this parameter input-wise.

It would be nice to use Acastus Photon as a relay for geo links with the q parameter, since its task is to resolve geo names to coordinates.

---

To ellaborate a bit what this parameter is supposed to do and what the problem with a lot of map apps is, here's a small example:

1. Create an appointment in Etar (Callendar)
2. Put "Street name 12, [postal code] [city name]" as event location
3. Click on the location in the finished event to open it in external maps app
4. Etar emits an intent url `geo:0,0?q=Street%20name%2012,%20[postal code]%20[city name]`

**Expected behavior**

* Maps app searches for "Street name 12, [postal code] [city name]"

**Usual behavior seen**

* Maps app navigates to geo coordinates 0,0 or says that the location could not be found

This behavior could be fixed in many apps by adding support for `geo:0,0?q=...` links to Acastus Photon:

1. App emits `geo:0,0?q=Street%20name%2012,%20[postal code]%20[city name]`
2. User opens the intent in Acastus Photon
3. AC resolves the geo coordinates of the place name received from `?q=...`
4. AC emits another intent with a regular google maps link with geo coordinates (this can be interpreted by most map apps)

If the location provided in `q` is fuzzy, AC could display the regular main activity with the query entered in the search bar to let the user choose the correct place.

**Comment by k3b** [comment]
I like the idea that Acastus becomes a translator

* from fuzzy geo uri-s (with search parameter but without latitude/longitude)
* to non fuzzy geo uri (with latitude/longitude)

-----

todo:

* if acastus catches a non-fuzzy-geo-uri it just reemits it so the next app can use this info.
* if acastus catches a fuzzy-geo-uri it loads the query "q=....." into the search field.

@leso-kn : is this the result you would expect?

* input geo:0,0?q=Hannover
* acastus gui: prefilled with search for : Hannover
* result geo:0,0?q=52.366667,9.716667(Hannover)

**Comment by leso-kn** [comment]
@k3b Yes, that's the result I would expect (except the coordinates go behind the colon, but I believe that's what you meant).

Ideally, if there's only one search result, the gui could be skipped and another intent could be triggered right away with the regarding geo coordinates.

**Comment by leso-kn** [comment]
On fuzzy search: I believe Google Maps and DB Navigator are two of the few apps that implement the `q=` parameter input-wise.

For testing the uri scheme, you can use [Etar](https://f-droid.org/de/packages/ws.xsoh.etar/) as described in the first post and your app "A photo manager" to open the event location. A photo manager does not support the `q=` parameter, but it will throw a toast message, that contains the full uri.

**Comment by leso-kn** [comment]
Finally, one problem I thought about earlier is: what if the user wants to set Acastus Photon as the default app to handle `geo:` links?
The app would just keep on triggering itself (considering the result is yet another `geo:` uri)

I'm not sure if this will be a problem, but if it does, it could be solved by adding a "default maps app" option in AP. Android Intents can [target specific apps](https://stackoverflow.com/a/27884672/4567685), this method could be used to pass the second `geo:` intent directlly to another app.

Example:

1. input `geo:0.0?q=Hannover` -> handled by Android system default (user-defined) app: in this case, Acastus Photon
2. acastus gui: prefilled with search for : Hannover (unless there's only one search result, in that case this step can be skipped)
3. result `geo:52.366667,9.716667(Hannover)` -> handled specifically by the app, that has been selected as default map application by the user (inside Acastus Photon)

**Comment by k3b** [comment]
on android 4.4 google maps app does not understand " geo:52.366667,9.716667(Hannover)" but this url works: "geo:0,0?q=52.366667,9.716667(Hannover)". I have not tested if that has changed with more recent versions

**Comment by k3b** [comment]
will be available in next release 1.24

**Comment by leso-kn** [comment]
Nice! Looking forward to it

**Comment by leso-kn** [comment]
Hi again!
I've tried the feature and it's working really well for fuzzy addresses so far
(address is unclear => AP opens the address picker dialog). Good job! :)

However, I've noticed it doesn't seem to work in cases where there's only one possible address
(address is clear => AP directly sends a location intent without the picker dialog in the middle)

I've attached three screenshots of a demo address where the address is in a very clear format (street, postal code, city). AP immediately finds the address, but the address in the intent seems to be incorrect:

<img width=32% src=https://user-images.githubusercontent.com/7886606/128162451-e32f579d-f519-4803-806a-a4b10f0c85b9.jpg /> <img width=32% src=https://user-images.githubusercontent.com/7886606/128162448-6b297025-d65a-4774-bd5c-2cba799b0a81.jpg /> <img width=32% src=https://user-images.githubusercontent.com/7886606/128162446-ecd3e3d9-e720-4840-97ad-5a934bd0cf39.jpg />

**Comment by leso-kn** [comment]
I think the problem with this is actually, that there's a comma (,) in the fuzzy address, that I've used to separate the street name and house number from the postal code and city.

The coordinates in the third screenshot display the postal code as part of the geo coordinates.

**Comment by k3b** [comment]
The Latest Version of the https://photon.komoot.io/ service now works with "Muckermannstraße 1, 60488 Frankfurt am Main"

**Comment by leso-kn** [comment]
Hey again! Thanks for the comma (,) fix in version 1.26! This is what I was referring to in [comment-8925](#issuecomment-892534836), maybe that was a bit unclear in the first place. Anyways, I can confirm that this is in fact fixed now 👍
