### ISSUE TITLE
Support for POI search other than addresses?

### ISSUE THREAD

**Issue by famo** [gjedeer/Acastus#17]
When I enter "hostel" or "fast food" for instance, I'm getting results from several thousands km away from my location. So I was wondering if this is supported by acastus?

**Comment by k3b** [comment]
when i search for "hostel berlin"  i get all hostels in berlin, germany

**Comment by famo** [comment]
> when i search for "hostel berlin" i get all hostels in berlin, germany

This does gives better results, but I doubt it's all hostels since I'm only getting 9 hits. Also I get "Berlín Eco Farm & Hostel" which is like 10.000 kilometers away...

In any case, this is unpractical: imagine one is traveling and wants to search for the nearest hostel, but doesn't even know the nearest town names...

**Comment by gjedeer** [comment]
@famo the question you should be asking is: if it's supported by [photon](https://photon.komoot.io/), which is the backend server Acastus uses.

I haven't really tried this use case, when looking for a particular category like hostels, my personal go-to was always OsmAnd categories search. Acastus does betters for addresses and place names (such as Beaten Goat Hostel Berlin or something)
