### ISSUE TITLE
Doesn't find some POI

### ISSUE THREAD

**Issue by letypequividelespoubelles** [gjedeer/Acastus#18]
Photon Acastus doesn't find some POI, for exemple : 
- try to search for "Cyrano Versailles movie theater / (cinéma in french) " or every combinaison / variation around it. It will never find [this POI](https://www.openstreetmap.org/node/206125584)
- try to search for "Papelli restaurant" and you'll find [this pizzeria](https://www.openstreetmap.org/node/6374047090). But if you serach for "Papelli Pizza" you'll find nothing

Thanks !

**Comment by gjedeer** [comment]
Hi,

Acastus displays search results from Photon backend. Please [check if your searches work in Photon](https://photon.komoot.io/) itself and if not, [file a bug in Photon](https://github.com/komoot/photon/issues) instead of Acastus.

Thanks for reporting.

**Comment by letypequividelespoubelles** [comment]
I just checked : it works perfectly for the Cyrano cinéma in Photon. 

For the issue with pizzeria / restaurant Papelli, I'l report in Photon itself, thanks.
