### ISSUE TITLE
A confusing icon on "Acastus-Photon" 's UI

### ISSUE THREAD

**Issue by b450mhdv** [gjedeer/Acastus#19]
@gjedeer 

Hello, I found a problem with the app's UI design. At first sight, I thought the widget near "Server" in the settings page is related to "refresh" without noticing its explanations. When I clicked on it, it took me to the "Server" setting page. I think the function of this icon is different from the common "refresh" icon I saw in other popular apps. This widget may confuse users. As a suggestion, if you can design a more intuitive icon, it may greatly improve the user experience. Could you fix this issue?

![Acastus-Photon](https://user-images.githubusercontent.com/78015408/128507144-79214cec-5115-4b69-b97b-c03754a98ddc.png)

**Comment by gjedeer** [comment]
@b450mhdv I agree, the icon was there when I forked the app and it's confusing. I have zero design skills though, so I won't replace it unless someone contributes a better one.

**Comment by k3b** [comment]
I replaced the "refresh" symbol with the android stock symbol "menu_mylocation"
