### ISSUE TITLE
Use as Geo-picker

### ISSUE THREAD

**Issue by k3b** [gjedeer/Acastus#2]
Is it possible to extend `Acastus Photon` so that it can serve as a geo-picker for other apps as described in https://github.com/k3b/k3b-geoHelper/wiki/Android-Geo-howto.

todo: 

* register in manifest for action "pick" for scheme "geo".
* In onCreate: if in picker mode show buttons ok/cancel
* onButtonOk return found geo-coordinate as activity-result

I have already implemented a geo-picker in [APhotoManager](https://github.com/k3b/APhotoManager/wiki) where you can pick a location either from a map or from a photo and i can do it for your app, too and send you a merge request if you want to.

**Comment by gjedeer** [comment]
Absolutely, please send a patch, I'll be happy to merge it.

Is it something unique to APhotoManager or is it an Android standard that I haven't heard about before? Not a problem if it's just your app, the patch is still welcome, just wanted to educate myself

**Comment by k3b** [comment]
pick-geo follows the intent-systematics but as far as i know my apps are the only one. i am lobbying for this to become a standard

**Comment by k3b** [comment]
In my branch https://github.com/k3b/Acastus/tree/k3b-wrk i have first changed the build environment and then implemented the geo picker.

I then cherry-picked geo-picker implementation back to master (without the change in gradle/android settings.

**Comment by gjedeer** [comment]
Alright, I'm probably going to merge the build changes later on too, I did not change these after forking and they're very outdated. But I don't have time to test them right now so just merging master.

**Comment by k3b** [comment]
implemented by merged https://github.com/gjedeer/Acastus/pull/4

**Comment by gjedeer** [comment]
Hey, @k3b can you write me an email, I cannot find a way to contact you privately.

**Comment by k3b** [comment]
high, i am k3b on github. 

In Use as Geo-picker · Issue #2 · gjedeer/Acastus you asked me for email contact. 

What can i do for you
  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
Use as Geo-picker · Issue #2 · gjedeer/Acastus
 Is it possible to extend Acastus Photon so that it can serve as a geo-picker for other apps as described in http...  |   |

  |

  |

 
 

    GDR! <notifications@github.com> schrieb am 10:40 Mittwoch, 28.November 2018:
 

 Hey, @k3b can you write me an email, I cannot find a way to contact you privately.—
