### ISSUE TITLE
Not working with OsmAnd on Android 6

### ISSUE THREAD

**Issue by gjedeer** [gjedeer/Acastus#22]
I got a bug report by email:

```
Hi!

After the last update (2022⁠‒⁠01⁠‒⁠02) Acastus‑Photon works only with GoogleMaps — but I use OsmAnd :(

Android‑6.0

With Regards
```

@k3b any ideas what you changed in the last release that may have caused this? I'll try to get some more info from the user

**Comment by gjedeer** [comment]
Looking at diffs from 1.24, only one line of actual code was changed, so it's likely an user's device problem. The changed line was in getting location, not in opening a map.

**Comment by k3b** [comment]
Which Version of osmDroid ?

This ist the only change that was mande: https://github.com/k3b/k3b-geoHelper/issues/7

i just installed the new acastus 1.2.6 it it works fine with osmand 3.9.10 on android-10

**Comment by gjedeer** [comment]
User confirmed it's their phone settings, closing the issue. Thanks for checking :)
