### ISSUE TITLE
"Location not enabled" error

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [gjedeer/Acastus#23]
It shows location not enabled when I try to share location.

**Comment by 1-minute-to-midnight** [comment]
I'd like to add that the location permission has been given and privacy guard shows that it has never requested for location despite this permission being set to allowed

**Comment by k3b** [comment]
@1-minute-to-midnight 
What Android version and device are you using?

On my android-10 (manufacturer LG) it works as expected?

**Comment by 1-minute-to-midnight** [comment]
Yeah I don't use the app nor the same device anymore so I'm gonna close this issue.
