### ISSUE TITLE
Adress management

### ISSUE THREAD

**Issue by ChfoSurGit** [gjedeer/Acastus#28]
Address management maps.google.ch or better: maps.google.*

**Comment by gjedeer** [comment]
Sorry?

**Comment by ChfoSurGit** [comment]
Hello,

The application supports links by image attachment.
A website that provides me with a maps.google.ch address is not supported.
Can you add this support in the application?

![Screenshot_20230617-141600_Paramètres](https://github.com/gjedeer/Acastus/assets/120626319/551bf013-c212-4f24-a71d-c423cc4f04fe)

**Comment by ChfoSurGit** [comment]
Oh!
Sorry, I'm on the wrong project.
Regards
