### ISSUE TITLE
translate vcard-contact info to geo

### ISSUE THREAD

**Issue by k3b** [gjedeer/Acastus#3]
Is it possible to register `Acastus Photon` as a view/send-to target for mime text/x-vcard so it can receive street/city from contact infos from contact-app or contact files and translates them to geo?

Workflow:

* In contact app select "peter meier from germany berlin alexanderplatz" and press the send button.
* in send target chooser select `Acastus Photon`
* `Acastus Photon` translates "berlin alexanderplatz" to a geo-point and sends it to a geo viewer

**Comment by gjedeer** [comment]
That's a nice idea.

I think it should build a query as structured as possible, with as much data as possible. So if you have a house number and postal code it would send:

alexanderplatz 8, 10178 berlin, germany

**Comment by k3b** [comment]
this would depend if your adress resolver supports this. I tried with street plus house nuber and got no result. after removing the house number it worked. maybe the house number was unknown.

**Comment by gjedeer** [comment]
Hmm, are you sure that vcard is the intent format? I'm looking at the source of the AOSP contacts app and it seems that it's sending a geo: uri

https://github.com/aosp-mirror/platform_packages_apps_contacts/blob/497a4359c644120bb197cd898a14a534bfbbd9e3/src/com/android/contacts/util/StructuredPostalUtils.java#L31

> Are there any rules for your adress-resolution provider how adress should be formatted

it seems that their tests cover all kind of user-provided madness:

https://github.com/geocoders/geocoder-tester/tree/master/geocoder_tester/world

But no, Photon isn't perfect, it's far from it actually. It's just the only remaining public API with a free server implementation that I've found. I too had varying luck in my searches.

**Comment by k3b** [comment]
I just tested with my android-7.1 smartphone using [Simple-Contacts](https://github.com/SimpleMobileTools/Simple-Contacts) as contact manager with as "sendto-menu" and [intent-intercept](https://github.com/k3b/intent-intercept) to see what is in the intent that simple contacts provide. i donot know if Simple-Contacts follow the standards and wether there are differences in different android-versions.

Intent-intercept reports mime-type="text/x-vcard". 

Interesting to see your example with geo-uri containing adress only but no lat/lon. this is the format used by the google-maps-app and the google-maps web page for the display-text https://github.com/k3b/k3b-geoHelper/wiki/data#geo

**Comment by k3b** [comment]
Solved with https://github.com/gjedeer/Acastus/issues/16 as current android-contact apps use geo-uri-s instead of VCard
